# Site settings
title: Jagger
subtitle: "Openness, Focus, First principles"
name: Jagger.H
email: jaggerwinner@gmail.com
description: >-
  Openness, Focus, First principles
url: "https://jaggerh.github.io"
baseurl: ""
repository: JaggerH/JaggerH.github.io

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"  # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Site author
author:
  name: "Jagger.H"
  bio: "Openness, Focus, First principles"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JaggerH"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jaggerwinner@gmail.com"

# Reading files
include:
  - _pages

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      sidebar:
        nav: "docs_sidebar"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
